# Generated by Django 3.1.4 on 2020-12-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('plate_no', models.CharField(max_length=20)),
                ('is_banned', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('started', models.DateField()),
            ],
        ),
    ]
